version: 2.1

aliases:
  - &save_yarn_cache
    name: Save yarn into the cache
    key: yarn-cache-{{ checksum "yarn.lock" }}-{{ arch }}
    paths:
      - ~/.cache/yarn
  - &restore_yarn_cache
    name: Restore yarn from the cache
    key: yarn-cache-{{ checksum "yarn.lock" }}-{{ arch }}
  - &restore_dependencies
    name: Restore node_modules from the cache
    key: node-cache-{{ checksum "yarn.lock" }}-{{ arch }}
  - &install_dependencies
    name: Install dependencies
    command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn
  - &save_dependencies
    name: Save node_modules into the cache
    key: node-cache-{{ checksum "yarn.lock" }}-{{ arch }}
    paths:
      - ./node_modules
      - ./native/node_modules
  - &install_bundler
    name: Install bundler
    command: |
      touch ~/.gemrc
      echo "gem: --no-document" >> ~/.gemrc
      sudo gem update --system
      sudo gem install bundler
  - &restore_gem_cache
    name: Restore gems from the cache
    key: gemfile-cache-{{ checksum "Gemfile.lock" }}-{{ arch }}
  - &install_gems
    name: Install gems
    command: |
      bundle config set --local deployment 'true'
      bundle install --jobs 2
  - &save_gem_cache
    name: Save gems into the cache
    key: gemfile-cache-{{ checksum "Gemfile.lock" }}-{{ arch }}
    paths:
      - vendor/bundle
  - &update_sdk_manager
    name: Update Android SDK Manager
    command: |
      echo 'Y' | sdkmanager "build-tools;30.0.2"
  - &accept_sdk_licenses
    name: Accept Android SDK Licences
    command: |
      echo 'Y' | sdkmanager --licenses
  - &decrypt_keystore_properties
    name: Decrypt keystore.properties
    command: |
      cd ./native/android
      openssl enc -aes-256-cbc -d -iter 1000 -in keystore.properties.encrypted -out keystore.properties -k ${ANDROID_KEYSTORE_PASSWORD}
  - &restore_pods_cache
    name: Restore Pods from the cache
    key: pods-v3-{{ checksum "native/ios/Podfile.lock" }}-{{ arch }}
  - &install_pods
    name: Install Pods
    command: |
      cd ./native
      yarn ios install-pods
  - &save_pods_cache
    name: Save Pods into the cache
    key: pods-v3-{{ checksum "native/ios/Podfile.lock" }}-{{ arch }}
    paths:
      - native/ios/Pods
  - &update_cocoapods
    name: Update cocoapods
    command: |
      sudo gem install cocoapods
  - &install_sentry_cli
    name: Install Sentry CLI
    command: |
      curl -sL https://sentry.io/get-cli/ | bash
  - &install_app_center_cli
    name: Install AppCenter CLI
    command: |
      sudo npm install appcenter-cli -g

jobs:
  ci-check:
    working_directory: ~/RNtemplate
    docker:
      - image: cimg/node:14.18

    shell: /bin/bash --login -eo pipefail

    steps:
      - checkout
      - restore_cache: *restore_yarn_cache
      - restore_cache: *restore_dependencies
      - run: *install_dependencies
      - save_cache: *save_dependencies
      - save_cache: *save_yarn_cache
      - run:
          name: CI
          command: |
            yarn tsc -p ./app/tsconfig.json
            yarn eslint ./app --ext .js,.jsx,.ts,.tsx --config ./app/.eslintrc.js --quiet
            yarn jest --forceExit --detectOpenHandles --passWithNoTests --runInBand
      - persist_to_workspace:
          root: ~/RNtemplate
          paths:
            - ./node_modules
            - ./app/node_modules
workflows:
  version: 2
  test-and-build:
    jobs:
      - ci-check
